// This file is generated by proute, do not edit it manually, it will be override

import { makeCreateMiddleware } from 'proute';
import routerConfig from './config';

export const createMiddleware = makeCreateMiddleware(routerConfig);